# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: API
    url: https://giftcardbd.shop/api/v1/ping
  - name: CDN
    url: https://cdn.giftcardbd.shop/ping
  - name: Shop
    url: https://giftcardbd.shop/ping

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Giftcardbd.shop**'s status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from all of our services.

